import "./styles/globals.css";
import Footer from "./components/footer/defaultFooters";
import Header from "./components/header/defaultHeaders";

export const metadata = {
  title: "DuckQuizz",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
